### ISSUE TITLE
Check data (tsvs) for converting to built-in datasets

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/datasauRus#1]
The tsvs are in extdata, we need to convert them to built in datasets but we need to check the file structure to see if it's a simple conversion

**Comment by LucyMcGowan** [comment]
I think `.tsv` i just tab separated so it should be a quick conversion with something like:

```
dat <- read.table("./inst/extdata/BoxPlots.tsv")
save(dat, file = "./inst/extdata/BoxPlots.Rda")
```

**Comment by stephlocke** [comment]
Lucy did this with PR #4 !
